/*RETO 3: ¿CUÁL ES EL PRIMER PRODUCTO QUE HA PEDIDO CADA CLIENTE?*/

USE [SQL_EN_LLAMAS_ALUMNOS]

SELECT 
	PRIMER_PRODUCTO,
	ID_CLIENTE
FROM (
	SELECT	
		S.CUSTOMER_ID AS ID_CLIENTE,
		M.PRODUCT_NAME AS PRIMER_PRODUCTO,
		ROW_NUMBER() OVER (PARTITION BY S.CUSTOMER_ID ORDER BY S.ORDER_DATE) AS ROW_NUM
	FROM [case01].[sales] S
	INNER JOIN [case01].[menu] M
		ON S.PRODUCT_ID = M.PRODUCT_ID
) AS SUBCONSULTA
WHERE ROW_NUM = 1;
