/*RETO 1: ¿CUÁNTO HA GASTADO EN TOTAL CADA CLIENTE EN EL RESTAURANTE?*/

USE [SQL_EN_LLAMAS_ALUMNOS]
GO

SELECT 
	C.CUSTOMER_ID AS ID_CLIENTE,
	CASE 
		WHEN SUM(PRICE) IS NULL 
			THEN 0
			ELSE SUM(PRICE)
	END AS TOTAL_GASTADO
FROM [case01].[menu] M
LEFT JOIN [case01].[sales] S
ON M.PRODUCT_ID = S.PRODUCT_ID
RIGHT JOIN [case01].[customers] C
ON S.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID

GO

