WITH VENTAS AS (
SELECT
	TXN_ID,
	SUM(QTY * PRICE * (100.0 - DISCOUNT)/100.0) AS PRECIO_TXN
FROM (SELECT DISTINCT * FROM CASE04.SALES) A
GROUP BY
	TXN_ID),

TABLA_PERCENTILES AS (
SELECT
	'CONTINUO' AS TIPO_PERCENTIL,
	PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY PRECIO_TXN) OVER () AS P_25,
	PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY PRECIO_TXN) OVER () AS P_50,
	PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY PRECIO_TXN) OVER () AS P_75
FROM VENTAS

UNION

SELECT
	'DISCRETO' AS TIPO_PERCENTIL,
	PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY PRECIO_TXN) OVER () AS P_25,
	PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY PRECIO_TXN) OVER () AS P_50,
	PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY PRECIO_TXN) OVER () AS P_75
FROM VENTAS)

SELECT *
FROM TABLA_PERCENTILES;
