--CALCULAMOS UNA LISTA DE ELEMENTOS POR TRANSACCION DE AQUELLAS QUE TENGAN MAS DE 3 ELEMENTOS ORDENADA ALFABÉTICAMENTE
WITH SALES_AGG AS 
(SELECT	
	TXN_ID,
	STRING_AGG('- ' + PRODUCT_NAME, CHAR(10)) WITHIN GROUP (ORDER BY PRODUCT_NAME) AS LISTA_COMPRA, --EL CHAR(10) ES PARA FORZAR EL SALTO DE LINEA, (AQUÍ NO SE VE PERO EN LA APP SI)
	COUNT(PRODUCT_NAME) AS NUM_ELEMENTOS
FROM CASE04.SALES A
JOIN CASE04.PRODUCT_DETAILS B ON A.PROD_ID = B.PRODUCT_ID
GROUP BY 
	TXN_ID
HAVING COUNT(PRODUCT_NAME) >=3),

--CALCULAMOS LAS VECES QUE SE REPITE CADA TRANSACCIÓN Y HACEMOS EL RANKING
SALES_AGG_VECES_REP AS
(SELECT 
	LISTA_COMPRA,
	NUM_ELEMENTOS,
	COUNT(LISTA_COMPRA) AS N_VECES_COMPRADO,
	RANK() OVER (ORDER BY COUNT(LISTA_COMPRA) DESC, NUM_ELEMENTOS DESC) AS RANK
FROM SALES_AGG
GROUP BY 
	LISTA_COMPRA,
	NUM_ELEMENTOS)

--MOSTRAMOS LA QUE MAS VECES SE REPITE
SELECT
N_VECES_COMPRADO,
CONCAT('La combinación más repetida es:',CHAR(10), LISTA_COMPRA) AS COMBINACION
FROM SALES_AGG_VECES_REP
WHERE RANK = 1;

/*********************************************************/
/***************** COMENTARIO MARÍA **********************/
/*********************************************************/
/*

Nice!

Resultado: OK
Código: OK.
Legibilidad: OK.


*/
