SELECT	C.CUSTOMER_ID,
	SUM(COALESCE(A.PRICE,0)) AS TOTAL_GASTADO
FROM	CASE01.MENU A
	LEFT OUTER JOIN CASE01.SALES B
		ON A.PRODUCT_ID=B.PRODUCT_ID
	RIGHT OUTER JOIN CASE01.CUSTOMERS C
		ON B.CUSTOMER_ID=C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID;
