WITH TABLA_PUNTOS AS
(SELECT
	C.CUSTOMER_ID,
	PRODUCT_NAME,
	PRICE,
	CASE WHEN PRODUCT_NAME = 'sushi' THEN PRICE * 20 ELSE PRICE * 10 END  AS PUNTOS
FROM CASE01.SALES A
LEFT OUTER JOIN  CASE01.MENU B ON A.PRODUCT_ID = B.PRODUCT_ID
RIGHT OUTER JOIN  CASE01.CUSTOMERS C ON A.CUSTOMER_ID = C.CUSTOMER_ID)

SELECT
	CUSTOMER_ID,
	COALESCE(SUM(PUNTOS),0) AS TOTAL_PUNTOS
FROM TABLA_PUNTOS
GROUP BY CUSTOMER_ID;


