SELECT
    AUX_FINAL.CUSTOMER_ID,
    STRING_AGG(AUX_FINAL.PRODUCT_NAME, ', ') PRODUCTO-- FUNCION PARA AGREGAR LOS PRODUCTOS EN UNA FILA POR CLIENTE
FROM 
--SUBSELECT DONDE SE OBTIENEN LOS CLIENTES Y LOS PEDIDOS POR FILA INDIVIDUAL
  (SELECT
        DISTINCT C.CUSTOMER_ID,
        COALESCE(D.PRODUCT_NAME,'No ha pedido') PRODUCT_NAME
    FROM
--SUBSELECT PARA SACAR LA FECHA MINIMA DE PEDIDO POR CLIENTE
        (SELECT
            CUSTOMER_ID,
            MIN(ORDER_DATE) MIN_FECHA
        FROM CASE01.SALES
        GROUP BY
            CUSTOMER_ID) AUX_PRIMERA_VISITA
    JOIN CASE01.SALES B 
    ON        AUX_PRIMERA_VISITA.CUSTOMER_ID = B.CUSTOMER_ID
            AND AUX_PRIMERA_VISITA.MIN_FECHA = B.ORDER_DATE
    RIGHT OUTER JOIN CASE01.CUSTOMERS C
    ON AUX_PRIMERA_VISITA.CUSTOMER_ID = C.CUSTOMER_ID
    LEFT OUTER JOIN CASE01.MENU D
    ON B.PRODUCT_ID = D.PRODUCT_ID) AUX_FINAL
GROUP BY
    AUX_FINAL.CUSTOMER_ID;
