SELECT 
    c.CUSTOMER_ID,
    COALESCE(SUM(CASE WHEN m.PRODUCT_NAME = 'sushi' THEN m.PRICE * 20 ELSE m.PRICE * 10 END), 0) AS PUNTOS
FROM 
    case01.customers c
LEFT JOIN 
    case01.sales s ON c.CUSTOMER_ID = s.CUSTOMER_ID
LEFT JOIN 
    case01.menu m ON m.PRODUCT_ID = s.PRODUCT_ID
GROUP BY 
    c.CUSTOMER_ID;
