CREATE OR ALTER PROCEDURE AMR_EJERCICIO_3_3_PROCEDURE

	@CUSTOMER_ID INTEGER,
	@MES INTEGER

AS

BEGIN
	DECLARE @TEXTO VARCHAR(100)
	DECLARE @GASTO AS DECIMAL (10,2)
--VER SI EXISTE EL CLIENTE
IF EXISTS 
		(SELECT CUSTOMER_ID 
		FROM CASE03.CUSTOMER_TRANSACTIONS 
		WHERE CUSTOMER_ID = @CUSTOMER_ID)
--SI EXISTE EL CLIENTE, VER SI NO EXISTE MES
	IF @MES < 1 OR @MES > 12 
--SI NO EXISTE EL MES SE GUARDA EL SIGUIENTE TEXTO
		SET @TEXTO = 'Elige un valor de mes valido (entre 1 y 12)' 
	ELSE
--SI EXISTE EL MES Y EL CLIENTE 
		BEGIN
		SELECT @GASTO = COALESCE(SUM(TXN_AMOUNT),0)
			FROM CASE03.CUSTOMER_TRANSACTIONS
		WHERE TXN_TYPE = 'PURCHASE'
			AND CUSTOMER_ID = @CUSTOMER_ID
			AND MONTH(TXN_DATE) = @MES
		SET @TEXTO = CONCAT('El cliente ',@CUSTOMER_ID,' se ha gastado un total de ',@GASTO,'€ en compras de productos en el mes de ',LOWER(DATENAME(MONTH,DATEFROMPARTS(2024,@MES,1))),'.')
		END
ELSE
--SI NO EXISTE EL CLIENTE SE GUARDA EL SIGUIENTE TEXTO
SET @TEXTO = CONCAT('No existe el cliente ',@CUSTOMER_ID) 
--POR ULTIMO, SE EJECUTA EL TEXTO GUARDADO
SELECT @TEXTO AS RESULTADO
END;

--PRUEBAS DEL PROCEDURE
EXECUTE AMR_EJERCICIO_3_3_PROCEDURE 1,3;
EXECUTE AMR_EJERCICIO_3_3_PROCEDURE 1,0;
EXECUTE AMR_EJERCICIO_3_3_PROCEDURE 0,1;

--SE ELIMINA EL PROCEDURE
DROP PROCEDURE IF EXISTS AMR_EJERCICIO_3_3_PROCEDURE;
