SELECT
	SALES.CUSTOMER_ID AS CUSTOMER,
	SUM(MENU.PRICE) AS PRICE
FROM
(SELECT * FROM SQL_EN_LLAMAS_ALUMNOS.case01.sales) SALES
LEFT JOIN
(SELECT * FROM SQL_EN_LLAMAS_ALUMNOS.case01.menu) MENU
ON SALES.PRODUCT_ID = MENU.PRODUCT_ID
GROUP BY SALES.CUSTOMER_ID;